### ISSUE TITLE
Implement clearsky filter

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#15] opened 2017-04-12 18:34 UTC
This should be done in a new module `filter.py`

**Comment by mdeceglie** [comment] 2017-04-12 18:44
Suggested that this is done with`pvlib.clearsky.detect_clearsky`, where the user supplies the detection parameters. We may also provide a tool for helping users identify appropriate parameters for their data.

**Comment by amnag** [comment] 2017-04-19 23:25
Added clearsky_filter branch to rdtools

**Comment by amnag** [comment] 2017-04-26 13:52
@danjruth,  in the updated filtering module, is it necessary to use tz_convert('utc') in a couple of lines ?

**Comment by danjruth** [comment] 2017-04-26 15:52
@amnag It doesn't look like it: the [PVLib documentation](http://pvlib-python.readthedocs.io/en/latest/timetimezones.html#pvlib-specific-functionality ) suggests that it can handle timezone-aware times, and will localize to UTC when given a timezone-naive time.

Should we just get rid of the conversion, or instead check that the timezone is not naive? I'm not sure how the rest of `rdtools` deals with timezones, but it may be worthwhile to ensure here that the timezone is localized, since that'll affect the clearsky irradiance values used in the filtering.

**Comment by amnag** [comment] 2017-04-26 17:02
We can check whether timezone info is available or not, if not we can set it to 'utc' ?
In get_clearsky_poa, this can be implemented as

if (clearsky.index.tzinfo is None):
   times = clearsky.index.tz_convert('utc')

In remove_cloudy_times, this can be implemented as
if (clearsky.index.tzinfo is None):
   irrad.index = irrad.index.tz_convert('utc')
   clearsky = get_clearsky_irrad(system_loc, irrad.index, correct_bin_labelling=correct_bin_labelling)

**Comment by danjruth** [comment] 2017-04-26 17:48
That works--I believe the second-to-last line should read `irrad.index = irrad.index.tz_localize('utc')`.

If it's not localized, would it be better to raise an error as opposed to assuming it should be in UTC? I could see forgetting to localize data before passing it to `remove_cloudy_times`, in which case it'd be helpful to have an error message.

**Comment by amnag** [comment] 2017-04-26 21:04
@danjruth, you're right, my bad

**Comment by amnag** [comment] 2017-04-27 14:56
I made the changes, can you please take a look and if possible test it ? I did test it and it works.

**Comment by danjruth** [comment] 2017-04-27 15:24
Looks good. I tested it with the `clearsky_test` notebook, and it threw the error when I didn't localize the times. Also it worked fine when I converted the times to UTC before passing the data to the filtering functions, provided I changed`start_time` and `end_time` appropriately.

I added the following to `detect_cloudy_days` to handle the case where there are no datapoints between `start_time` and `end_time` for a given day:
```
# call a day cloudy if there are no valid points to look at between start_time and end_time
        if (num_false+num_true)==0:
            clear_days[date] = False
        else:
            clear_days[date] = float(num_true)/float(num_false+num_true) >= thresh
```

**Comment by amnag** [comment] 2017-05-22 16:19
@danjruth and @mdeceglie, can you please take a look at the updated filtering.py code in the clearsky_filter branch of rdtools? I had to make some changes in get_clearsky_irrad function because a collections.OrderedDict object was assigned to clearsky and this was creating problems with the remove_cloudy_times function.

**Comment by wholmgren** [comment] 2017-05-23 17:27
your error might be related to https://github.com/pvlib/pvlib-python/pull/326

I'll make a new release when I get a chance.

**Comment by cdeline** [comment] 2017-07-05 19:59
@mdeceglie  At this point can we combine the clearsky temperature with the clearsky_filter branch?  Are these two branches accomplishing effectively the same workflow?

**Comment by mdeceglie** [comment] 2017-07-07 15:23
I'm haven't followed development on those branches in great detail. In the next week or so I will convene a meeting to kick-off the effort to polish consolidate the clear-sky workflow.

**Comment by mdeceglie** [comment] 2017-07-18 18:02
@GregoryKimball I pushed a new branch '[basic_clearsky_workflow](https://github.com/NREL/rdtools/tree/basic_clearsky_workflow)'. Would you mind taking a look at the new example notebook to make sure I got the workflow correct? We still need to add unit tests for the new functions before merging.

**Comment by GregoryKimball** [comment] 2017-07-21 01:36
@mdeceglie Thank you for your great work on this branch.  I'm working on a number of follow-up topics right now:

 - I'm not familiar with the `pvlib.irradiance` workflow used in the notebook.  I have more experience computing components by `pvlib.clearsky.ineichen`, `pvlib.irradiance.king` and ` pvlib.irradiance.grounddiffuse` and then combining to POA with `pvlib.irradiance.globalinplane`.  
 - Does the notebook include linke turbidity losses?  I'm not sure yet.
 - 'normalized power' after Step 3 shows a lot of very poor performance index.  What is the root cause? 
 - Irradiance-weighted performance seems like a good idea, but I haven't reviewed `rdtools.aggregation_insol` in detail.
 - Interesting that OLS shows smaller confidence interval than YOY for this PV system.  Are all intervals reported at 95% confidence?
 - I typically have aggregated the 15-min data into weekly medians, rather than daily irradiance-weighted means.  When I looked into standard deviation of YOY deltas as a function of aggregation length, I found 7-14 days to give the lowest values.
 - How does the 15-min YOY histogram fit into the workflow?

Haha, maybe this discussion should evolve into a meeting.

**Comment by mdeceglie** [comment] 2017-07-21 16:23
Thanks for your help @GregoryKimball. I'm happy to connect on the phone if that would be helpful. For now:

1. The irradiance transposition is the simple isotropic sky and ignores the ground. This could be made more detailed (but do we need to? Does it improve degradation calculations, especially in the clear sky case?) I would tend to use haydavies or perez for a more detailed model
2. The `get_clearsky()` method of a pvlib location uses ineichen by default and, if I interpreted [the source](https://pvlib-python.readthedocs.io/en/latest/_modules/pvlib/location.html#Location.get_clearsky) correctly, automatically looks up the linke turbidity.
3. OK on the wind. That't the type of flexibility we hope to support
4. I'll also look into step 3
5. OK let us know what you think of the aggregation
6. All confidence intervals are 68.2%, whether they are directly comparable is still debatable though.
7. `aggregation_insol()` supports different aggregation frequencies so this should be no problem. If that is the aggregation time we'd like to steer folks to as a starting point.
8.  Good catch. Those histograms at the end are mislabeled, they are daily values. I'll open an issue, once we get this merged we can fix it in both notebooks.

Thanks again!

**Comment by mdeceglie** [comment] 2017-07-27 22:08
Regarding item 4: I believe the root cause is down to angle of incidence (AOI). See the plot below. We could add a filter for AOI <60. But this doesn't change the end YOY calculation much. The 
YOY results are

- without AOI filter:  -0.81 %/year with a confidence interval of -0.91 to -0.75 %/year

- with AOI<60 filter:  -0.85 %/yearwith a confidence interval of -0.93 to -0.75 %/year

So the median moves slightly and the confidence interval gets a little larger. Given there is no clear benefit, I suggest omitting the AOI filter. One of the great advantages of YOY is that you don't have to develop detailed filters. Thoughts?

![aoi](https://user-images.githubusercontent.com/12532260/28694020-c81e0c7c-72e4-11e7-913f-b8f4633d9bc2.png)

**Comment by GregoryKimball** [comment] 2017-07-28 15:16
@mdeceglie I'm writing some tests to study the workflow with other sources of input data and I will send an update as soon as possible.

**Comment by mdeceglie** [comment] 2017-08-18 22:33
@GregoryKimball I think most of the changes look good. If I understand correctly, update 4 is in the example notebook? I suggest leaving out code to handle trackers since our example system is fixed tilt. Perhaps a different example could be developed to show how to work with trackers? I don't think that applying rdtools to tracker data requires updates to the rdtools functions themselves.

**Closed** 2017-10-01 02:50 UTC
