### ISSUE TITLE
improve rdtools import time

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/rdtools#155] opened 2020-03-17 15:45 UTC
RdTools is a little slow to import:

```
In [1]: %time import rdtools
Wall time: 1.04 s
```
For comparison:
```
In [1]: %time import pvlib
Wall time: 184 ms
```

Here's a breakdown of where `import rdtools` is spending time:

![image](https://user-images.githubusercontent.com/57452607/76869991-b86a9b00-682e-11ea-8af4-a1f0925a495d.png)

Generated with:
```
(base) C:\Windows\Temp>python -X importtime -c "import rdtools" 2> rdtools.log
(base) C:\Windows\Temp>tuna rdtools.log
```

We could speed up the import time by changing how we import packages.  I notice that `statsmodels.api`, `pkg_resources`, and `h5py` together make up a large chunk of the total but aren't actually used in the "primary" RdTools functions.  What do people think about moving those imports into the functions that need them instead of importing at module scope?

Pros:
- It decreases import time to 600 ms (~40% speedup) on my machine
- It makes those dependencies optional for people that don't plan on using those functions -- e.g. our fleets pipeline doesn't actually need the statsmodels package because it doesn't use the OLS and classical decomp functions. 

Cons:
- It's nice to have a list of imports at the top of the module and hiding them in the functions is nonstandard and reduces code clarity
- It violates pep8 (https://www.python.org/dev/peps/pep-0008/#imports)
- It makes the first function invocation slower, and subsequent invocations very marginally slower
- 1 second to import isn't that big a deal

**Comment by cwhanse** [comment] 2020-03-17 16:26
@kanderso-nrel  that's a cool figure. How should I interpret the vertical ordering? Going down the pvlib stack, pvlib is 11.89% of RdTools import time, and within pvlib, pvlib.tracking is 10.5% of RdTools total import time (i.e., ~90% of the pvlib import time).  Next is pvlib.pvsystem - is this below pvlib.tracking because pvlib.tracking uses pvlib.pvsystem? Or is pvlib.pvsystem the next longest import time, in which case, I don't know how to interpret import time of 0.283s (10.4%).

**Comment by kanderso-nrel** [comment] 2020-03-17 16:58
@cwhanse yeah, it's a little tricky to interpret that chart because it tracks time spent on an actual full import, so its organization is driven by the ordering inside `__init__.py` files.  You'll notice that pandas only shows up under `rdtools.normalization` despite being an import in most of the other submodules in rdtools (and pvlib) because `rdtools.normalization` happens to be the first thing to need pandas and subsequent pandas imports just hit the cache.  For instance `rdtools.normalization` imports pandas before it imports pvlib, so when pvlib gets imported, it doesn't have to spend any time on pandas.  By switching the order so that pvlib is imported before pandas, the pandas block moves under `pvlib.tools` and pvlib expands to becomes the majority of `rdtools.normalization`. 

> Next is pvlib.pvsystem - is this below pvlib.tracking because pvlib.tracking uses pvlib.pvsystem?

Correct, when combined with the fact that pvlib's `__init__.py` imports tracking *before* pvsystem and singlediode.  Since `pvlib.tracking` imports `pvlib.pvsystem`, which imports `pvlib.singlediode`, which imports `scipy.optimize`, all of that gets filed under `pvlib.tracking`.

(I happen to be using 0.6.1 for this): https://github.com/pvlib/pvlib-python/blob/v0.6.1/pvlib/__init__.py

**Comment by mdeceglie** [comment] 2020-03-17 20:04
Thanks for starting the discussion on this @kanderso-nrel. 

I'm hesitant to remove any requirements from setup.py. Manually installing packages when an error arises is a common frustration for many folks with limited python experience.

Could still move the imports into the functions, though it may make things harder to maintain.

As a note, I believe `statsmodels` is only used for linear regression, so we may be able to get by with another package that imports more quickly.

**Comment by kanderso-nrel** [comment] 2020-03-17 20:21
> I'm hesitant to remove any requirements from setup.py. Manually installing packages when an error arises is a common frustration for many folks with limited python experience.

I agree that we should try to minimize frustration from package management.  I didn't mean removing them from setup.py altogether, I meant moving them to an "optional" list like the way pvlib handles the `tables` package -- import in a function, and raise a helpful error message if it's not installed:
- import in function: https://github.com/pvlib/pvlib-python/blob/master/pvlib/clearsky.py#L188 
- setup.py entry: https://github.com/pvlib/pvlib-python/blob/master/setup.py#L47

The error message could say something like `The 'XYZ' package is not installed.  You can install it with 'pip install XYZ', or you can run 'pip install rdtools[optional]' to install all optional packages`.  

> As a note, I believe statsmodels is only used for linear regression, so we may be able to get by with another package that imports more quickly.

Good point, though that's an actual change instead of just minor restructuring.  Maybe `np.polyfit`?

**Comment by cwhanse** [comment] 2020-03-17 20:43
> Good point, though that's an actual change instead of just minor restructuring.  Maybe np.polyfit?

My $0.02: unless importing statsmodels becomes a performance headache, I'd stick with it for the long term. There are regression functions in numpy (`numpy.linalg.lstsq`) but my sense is that the long-term intent is to provide regression and similar functions in statsmodels and scipy, with numpy providing the building blocks. And statsmodels provides options such as robust regression that may become desireable for RdTools applications.

**Comment by mdeceglie** [comment] 2021-03-05 22:25
This is almost a year old and the marginal gains probably don't justify violating style guides to put imports in functions. I'll close this for now.

**Closed by mdeceglie** 2021-03-05 22:25 UTC
